Debug:	2024/07/25 10:50:30 logger.go:34: Ошибки тоже нет 123
Debug:	2024/07/25 10:51:23 logger.go:34: Ошибки тоже нет 123
Debug:	2024/07/25 10:53:34 logger.go:34: Ошибки тоже нет 123
Debug:	2024/07/25 10:59:35 logger.go:45: Ошибки тоже нет%!(EXTRA int=123)
Debug:	2024/07/25 11:29:32 logger.go:40: неудача при выполнении GET-запроса на эндпоинт /info Get "https://localhost/info?passportSerie=1234&passportNumber=567895": dial tcp [::1]:443: connect: connection refused
Debug:	2024/07/25 11:29:58 logger.go:40: неудача при выполнении GET-запроса на эндпоинт /info Get "https://localhost/info?passportSerie=1234&passportNumber=567895": dial tcp [::1]:443: connect: connection refused
Debug:	2024/07/25 11:29:58 logger.go:40: неудача при добавлении данных в БД паспортные данные есть в БД
Debug:	2024/07/25 11:30:36 logger.go:40: неудача при выполнении GET-запроса на эндпоинт /info Get "https://localhost/info?passportSerie=1234&passportNumber=567896": dial tcp [::1]:443: connect: connection refused
Debug:	2024/07/25 11:32:34 logger.go:40: неудача при выполнении GET-запроса на эндпоинт /info Get "https://localhost/info?passportSerie=1234&passportNumber=567897": dial tcp [::1]:443: connect: connection refused
Debug:	2024/07/25 11:32:44 logger.go:40: неудача при выполнении GET-запроса на эндпоинт /info Get "https://localhost/info?passportSerie=1234&passportNumber=567898": dial tcp [::1]:443: connect: connection refused
Debug:	2024/07/25 11:42:37 logger.go:40: неудача при выполнении GET-запроса на эндпоинт /info Get "https://localhost/info?passportSerie=1234&passportNumber=567899": dial tcp [::1]:443: connect: connection refused
Debug:	2024/07/25 11:42:37 logger.go:40: Обогощение данных со стороннего API не выполнено
Debug:	2024/07/25 11:51:48 logger.go:40: в базе данных нет новых миграций для применения no change
Debug:	2024/07/25 12:10:24 logger.go:40: в базе данных нет новых миграций для применения no change
Debug:	2024/07/25 12:10:43 logger.go:40: неудача при выполнении GET-запроса на эндпоинт /info Get "https://localhost/info?passportSerie=1234&passportNumber=567899": dial tcp [::1]:443: connect: connection refused
Debug:	2024/07/25 12:10:43 logger.go:40: Обогощение данных со стороннего API не выполнено
Debug:	2024/07/25 12:10:43 logger.go:40: человек с данным паспортом есть в БД: 1234 567899
Debug:	2024/07/25 12:10:43 logger.go:40: неудача при добавлении данных в БД паспортные данные есть в БД
Debug:	2024/07/25 12:13:31 logger.go:40: человек с данным паспортом есть в БД: 1234 567899
Debug:	2024/07/25 12:14:29 logger.go:40: человек с данным паспортом есть в БД: 1234 567891
Debug:	2024/07/25 12:16:29 logger.go:40: метод запроса не GET, а PUT
Debug:	2024/07/25 12:17:18 logger.go:40: в базе данных нет новых миграций для применения no change
Debug:	2024/07/25 12:19:57 logger.go:40: в базе данных нет новых миграций для применения no change
